import 'dart:convert';

import 'package:json_annotation/json_annotation.dart';

part 'event.g.dart';

/// Canonical JSON (de)serialization for [Event] is generated by
/// json_serializable ([fromJson]/[toJson]) and used for local caching.
///
/// PocketBase wire records keep using [fromMap]/[toMap], which tolerate the
/// server's flexible encodings (ISO strings, JSON-encoded arrays, expand).
@JsonSerializable()
class Event {
  final String? id;
  final String title;
  final String? description;
  final DateTime start;
  final DateTime end;
  final String? venueId;
  final List<String> performers;
  final String? createdBy;

  /// Server-managed PocketBase `created` autodate. Never sent on write.
  final DateTime created;

  /// Resolved from PocketBase `expand` — display names, not IDs.
  final String? venueName;
  final List<String> performerNames;

  Event({
    this.id,
    required this.title,
    this.description,
    required this.start,
    required this.end,
    this.venueId,
    this.performers = const [],
    this.createdBy,
    DateTime? created,
    this.venueName,
    this.performerNames = const [],
  }) : created = created ?? DateTime.now();

  Map<String, dynamic> toMap() {
    // Write explicit UTC instants: queries (month bounds, overlap checks) are
    // built from `.toUtc()` strings, so naive local times would misalign at
    // month boundaries. Display code converts back via `.toLocal()`.
    return {
      'title': title,
      'description': description,
      'start': start.toUtc().toIso8601String(),
      'end': end.toUtc().toIso8601String(),
      'venueId': venueId,
      'performers': performers,
      'createdBy': createdBy,
    };
  }

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);

  Map<String, dynamic> toJson() => _$EventToJson(this);
  factory Event.fromMap(Map<String, dynamic> data, [String? id]) {
    DateTime parseDate(dynamic v) {
      if (v == null) return DateTime.now();
      if (v is DateTime) return v;
      if (v is String) {
        final p = DateTime.tryParse(v);
        return p ?? DateTime.now();
      }
      return DateTime.now();
    }

    List<String> parseStringList(dynamic v) {
      if (v == null) return [];
      if (v is List) return v.map((e) => e?.toString() ?? '').where((s) => s.isNotEmpty).toList();
      if (v is String) {
        final s = v.trim();
        if (s.isEmpty) return [];
        // try parse JSON array string
        try {
          final parsed = jsonDecode(s);
          if (parsed is List) return parsed.map((e) => e?.toString() ?? '').where((s) => s.isNotEmpty).toList();
        } catch (_) {}
        // fallback: comma-separated
        return s.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
      }
      // any other type -> single-element list of its string repr
      return [v.toString()];
    }

    String? venueName;
    List<String> performerNames = const [];
    final expand = data['expand'];
    if (expand is Map) {
      final venue = expand['venueId'];
      if (venue is Map) {
        venueName = (venue['name'] ?? venue['title'] ?? venue['id'] ?? '').toString();
      }
      final expandedPerformers = expand['performers'];
      if (expandedPerformers is List) {
        performerNames = expandedPerformers.map((p) {
          if (p is Map) return (p['name'] ?? p['title'] ?? p['id'] ?? '').toString();
          return p?.toString() ?? '';
        }).where((s) => s.isNotEmpty).toList();
      }
    }

    return Event(
      id: id,
      title: data['title'] ?? '',
      description: data['description'],
      start: parseDate(data['start']),
      end: parseDate(data['end']),
      venueId: data['venueId'],
      performers: parseStringList(data['performers']),
      createdBy: data['createdBy'],
      created: parseDate(data['created']),
      venueName: venueName,
      performerNames: performerNames,
    );
  }
}
