import 'dart:async';

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

import '../data/repositories.dart';
import '../l10n/app_localizations.dart';
import '../nav/destinations.dart';
import '../router.dart';
import '../router_paths.dart';
import '../services/pocketbase_service.dart';
import '../utils/error_text.dart';

/// Email/password sign-in against the PocketBase `users` collection.
///
/// The redirect in lib/router.dart owns navigation away from this page once a
/// session exists, so this screen only reports failures and never pushes to
/// another route itself.
class UserSelectPage extends StatefulWidget {
  const UserSelectPage({super.key});

  @override
  State<UserSelectPage> createState() => _UserSelectPageState();
}

class _UserSelectPageState extends State<UserSelectPage> {
  final _email = TextEditingController();
  final _password = TextEditingController();
  bool _submitting = false;
  bool _obscure = true;

  /// Whether this server offers guest sign-in, and whether we have asked yet.
  ///
  /// Three states, not two, because "not asked" must not look like "no": the
  /// probe is a network round-trip, and rendering the button's absence during it
  /// would make the button flicker in on a slow link. Null = still asking.
  bool? _guestAvailable;

  @override
  void initState() {
    super.initState();
    unawaited(_probeGuest());
  }

  /// Asks whether guest sign-in is enabled (see `pb_hooks/guest.pb.js`).
  ///
  /// Best-effort and silent: a failure reads as "not offered", so an unreachable
  /// backend costs the user the guest button and nothing else — the ordinary
  /// sign-in form is still right there and reports the real problem when used.
  Future<void> _probeGuest() async {
    final available = await PocketBaseService.shared.guestEnabled();
    if (!mounted) return;
    setState(() => _guestAvailable = available);
  }

  @override
  void dispose() {
    _email.dispose();
    _password.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_submitting) return;
    final l10n = AppLocalizations.of(context);
    final email = _email.text.trim();
    final password = _password.text;
    if (email.isEmpty || password.isEmpty) {
      _showMessage(l10n.enterEmailAndPassword);
      return;
    }

    setState(() => _submitting = true);
    final session = context.read<SessionController>();
    String? error;
    try {
      // Distinguishes "backend unreachable" from "wrong password": a null
      // result is a credential rejection, a thrown error is a transport or
      // server failure, and the user needs to be told which.
      final user = await session.login(email, password);
      if (user == null) error = l10n.invalidCredentials;
    } catch (e) {
      error = errorText(l10n, e);
    }
    if (!mounted) return;
    setState(() => _submitting = false);
    if (error != null) {
      _showMessage(error);
      return;
    }
    await _enterApp();
  }

  /// Enters the app signed in as a throwaway demo guest.
  ///
  /// Nothing is read from the form: the address and password are generated by
  /// [SessionController.loginAsGuest], which is the point of the button — the
  /// two fields that make signing in tiresome are exactly the two this path does
  /// not need. A guest is an ordinary account (see `pb_hooks/guest.pb.js`), so
  /// everything after this point is the same as any other sign-in.
  ///
  /// The failure wording matters more here than on the form above: the user did
  /// not choose the credentials, so an error is never their fault and must say
  /// what actually happened (rate limited, switched off server-side, backend
  /// unreachable) rather than blaming an empty field.
  Future<void> _submitGuest() async {
    if (_submitting) return;
    final l10n = AppLocalizations.of(context);
    setState(() => _submitting = true);
    String? error;
    try {
      await context.read<SessionController>().loginAsGuest(
        // Named so the dashboard reads "Painel — Visitante" rather than
        // "Painel — guest-1758...", which would look like a bug to the person
        // being shown the app.
        name: l10n.guestAccountName,
      );
    } catch (e) {
      error = errorText(l10n, e);
    }
    if (!mounted) return;
    setState(() => _submitting = false);
    if (error != null) {
      _showMessage(error);
      return;
    }
    await _enterApp();
  }

  /// Warms the session's data and leaves for the app's home.
  ///
  /// Shared by both ways in, because the tail is not sign-in-specific: whatever
  /// produced a session, the next screen should not open on a spinner, and the
  /// destination is the router's decision (see [kHomeLocation]).
  Future<void> _enterApp() async {
    // Warm the assignments before leaving, so the screen that lands does not
    // open on a spinner while its own load runs.
    try {
      await context.read<AssignmentsController>().refresh();
    } catch (_) {
      // Advisory: the landing screen loads them itself and reports its own
      // failure.
    }
    if (!mounted) return;
    context.go(kHomeLocation);
  }

  void _showMessage(String message) {
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(message)));
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return Scaffold(
      appBar: AppBar(title: Text(l10n.signIn)),
      body: Center(
        child: SingleChildScrollView(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 420),
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  TextField(
                    controller: _email,
                    keyboardType: TextInputType.emailAddress,
                    autofillHints: const [AutofillHints.email],
                    textInputAction: TextInputAction.next,
                    decoration: InputDecoration(labelText: l10n.email),
                  ),
                  const SizedBox(height: 16),
                  TextField(
                    controller: _password,
                    obscureText: _obscure,
                    autofillHints: const [AutofillHints.password],
                    textInputAction: TextInputAction.done,
                    onSubmitted: (_) => _submit(),
                    decoration: InputDecoration(
                      labelText: l10n.password,
                      suffixIcon: IconButton(
                        icon: Icon(
                          _obscure ? Icons.visibility : Icons.visibility_off,
                        ),
                        onPressed: () => setState(() => _obscure = !_obscure),
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  FilledButton(
                    onPressed: _submitting ? null : _submit,
                    child: _submitting
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : Text(l10n.signIn),
                  ),
                  const SizedBox(height: 8),
                  TextButton(
                    onPressed: _submitting ? null : () => context.go('/signup'),
                    child: Text(l10n.signUpAction),
                  ),
                  // Guest sign-in, offered only when the server says it is on
                  // (see `pb_hooks/guest.pb.js`). Null means the probe has not
                  // answered yet, and that renders exactly like `false`: a
                  // button that materialises a moment after the screen does is
                  // worse than one that arrives with the answer, and on a
                  // deployment where it is off it must never appear at all.
                  if (_guestAvailable ?? false) ...[
                    const SizedBox(height: 8),
                    OutlinedButton.icon(
                      onPressed: _submitting ? null : _submitGuest,
                      icon: const Icon(Icons.rocket_launch_outlined),
                      label: Text(l10n.guestSignIn),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      l10n.guestSignInHint,
                      textAlign: TextAlign.center,
                      style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: Theme.of(context).colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                  // Carries whatever is already typed in the email field, so the
                  // common case — you typed your address, the password was wrong,
                  // you remember a different one — needs no retyping. Reads the
                  // controller at tap time rather than watching it, so the
                  // button does not rebuild on every keystroke.
                  TextButton(
                    onPressed: _submitting
                        ? null
                        : () => context.go(
                            forgotPasswordPath(email: _email.text),
                          ),
                    child: Text(l10n.forgotPassword),
                  ),
                  const Divider(height: 40),
                  // Both public lists, not just venues: an act looking for
                  // their band has no reason to care about rooms. Stacked
                  // rather than side by side — two labelled buttons in one row
                  // overflow a narrow phone, and this column is already
                  // max-width constrained rather than scrollable horizontally.
                  TextButton.icon(
                    onPressed: _submitting
                        ? null
                        : () => context.go(venuesBrowsePath()),
                    icon: Icon(Destinations.venues.icon),
                    label: Text(l10n.browseVenues),
                  ),
                  TextButton.icon(
                    onPressed: _submitting
                        ? null
                        : () => context.go(performersBrowsePath()),
                    icon: Icon(Destinations.performers.icon),
                    label: Text(l10n.browsePerformers),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
